# Generated by Django 3.0.2 on 2020-01-20 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='phone',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.PROTECT, to='account.Phone', verbose_name='Мобільний телефон'),
        ),
    ]
