# Generated by Django 3.0.2 on 2020-01-20 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20200120_1915'),
        ('account', '0002_auto_20200120_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='phone',
            field=models.CharField(blank=True, max_length=12, unique=True, verbose_name='Номер телефону'),
        ),
        migrations.DeleteModel(
            name='Phone',
        ),
    ]
