# Generated by Django 3.0.2 on 2020-01-20 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20200120_2100'),
        ('account', '0003_auto_20200120_1915'),
    ]

    operations = [
        migrations.CreateModel(
            name='FastCostumer',
            fields=[
                ('order_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='order.Order')),
            ],
            options={
                'verbose_name': 'Тимчасовий покупець',
                'verbose_name_plural': 'Тимчасові покупці',
            },
            bases=('order.order',),
        ),
    ]
