export const API_URL = "http://eatmeapi.herokuapp.com/api";

export const GET_CATEGORIES = "GET_CATEGORIES";
export const GET_CATEGORIES_SUCCESS = "GET_CATEGORIES_SUCCESS";
export const GET_CATEGORIES_FAILURE = "GET_CATEGORIES_FAILURE";

export const GET_CUISINES = "GET_CUISINES";
export const GET_CUISINES_SUCCESS = "GET_CUISINES_SUCCESS";
export const GET_CUISINES_FAILURE = "GET_CUISINES_FAILURE";

export const FILTER_CATEGORIES_GET = "FILTER_CATEGORIES_GET";
export const FILTER_CATEGORIES_CHECKED = "FILTER_CATEGORIES_CHECKED";
export const FILTER_CATEGORIES_UNCHECKED_ALL = "FILTER_CATEGORIES_UNCHECKED_ALL";
