# Generated by Django 3.0.2 on 2020-04-18 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryEstablishment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Назва')),
            ],
            options={
                'verbose_name': 'Категорія Закладу',
                'verbose_name_plural': 'Категорія Зкаладів',
            },
        ),
        migrations.AlterField(
            model_name='cuisine',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Назва'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='image',
            field=models.URLField(blank=True, null=True, verbose_name='Зображення'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='image',
            field=models.URLField(blank=True, null=True, verbose_name='Зображення'),
        ),
        migrations.AddField(
            model_name='institution',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='menu.CategoryEstablishment', verbose_name='Категорія закладу'),
        ),
    ]
