# Generated by Django 3.0.2 on 2020-04-18 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20200418_1137'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoryestablishment',
            options={'verbose_name': 'Категорія Закладу', 'verbose_name_plural': 'Категорія Зaкладів'},
        ),
    ]
