# Generated by Django 3.0.2 on 2020-01-20 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paymentMethod', models.CharField(blank=True, choices=[('cash', "Оплата готівкова кур'єру"), ('cashless', "Оплата безготівкова кур'єру"), ('online', 'Оплата онлайн')], default='online', max_length=50, verbose_name='Спосіб оплати')),
                ('orderTime', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата замовлення')),
                ('paid', models.BooleanField(default=False, verbose_name='Оплата')),
                ('customerPhone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='account.Phone', verbose_name='Телефон')),
                ('fullName', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='fullName', to='account.Account', verbose_name='Замовник')),
                ('orderList', models.ManyToManyField(blank=True, to='menu.Dish', verbose_name='Зміст замовлення')),
            ],
            options={
                'verbose_name': 'Замовлення',
                'verbose_name_plural': 'Замовлення',
            },
        ),
    ]
