# Generated by Django 3.0.2 on 2020-01-20 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customerPhone',
            field=models.CharField(blank=True, default='', max_length=12, unique=True, verbose_name='Номер телефону'),
        ),
    ]
