# Generated by Django 3.0.2 on 2020-04-18 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='totalPrice',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Сума замовлення'),
        ),
        migrations.AddField(
            model_name='order',
            name='totalQuantity',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Всього страв'),
        ),
    ]
