# Generated by Django 3.0.2 on 2020-01-20 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20200120_1915'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='fullName',
        ),
        migrations.AddField(
            model_name='order',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Замовник'),
        ),
        migrations.AddField(
            model_name='order',
            name='surname',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Прізвище'),
        ),
    ]
