# Generated by Django 3.0.2 on 2020-01-20 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20200120_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name="Ім'я"),
        ),
    ]
