# Generated by Django 3.0.2 on 2020-05-19 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_auto_20200424_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID користувача'),
        ),
    ]
